const assert = require('node:assert/strict');
const fs = require('node:fs');
const {WorldEngine, EventBus, SaveSystem} = require('../mindcrafted/engine/world/core.js');
const BKT = require('../mindcrafted/engine/bkt.js');
const world = JSON.parse(fs.readFileSync(0, 'utf8'));
const e = new WorldEngine(world), observations = [];
e.events.on('learning.observation', event => observations.push(event));
assert.equal(e.interact('routing_A'), false, 'Remote interaction must fail');
assert.equal(e.interact('routing_mentor'), false);
assert.ok(e.move('right'));
assert.ok(e.interact('routing_mentor'));
assert.equal(e.move('right'), false, 'Dialogue should pause movement');
e.advanceDialogue();
assert.equal(e.state.quests.routing_quest, 'active');
const p = e.puzzles.get('routing'), s = e.state.puzzles.routing;
// Unit-level arrangement isolates arbitration from pathfinding (covered by walkthrough/E2E).
s.routes = {A: 'B', E: 'B', F: 'B', G: 'B', B: 'D', C: 'D'};
e.state.player = {x: 6, y: 9};
assert.ok(e.interact('routing_console'));
assert.equal(s.solved, false);
assert.equal(e.state.flags.routing_restored, undefined);
assert.deepEqual(s.routes, {}, 'Failed attempt automatically resets controls');
assert.equal(s.congestionEvents, 1);
assert.equal(observations.find(o => o.skill === 'network.load_balance').correct, false);
assert.equal(observations.find(o => o.skill === 'network.routing').correct, true);
assert.equal(observations[0].observations.solutionSteps, 1, 'Submission is a recorded solution action');
assert.ok(observations[0].observations.correctActions > 0);
assert.ok(observations[0].observations.invalidActions > 0);
assert.ok(Number.isFinite(observations[0].observations.solutionTimeMs));
e.hint();
assert.equal(s.hintsUsed, 1);
s.routes = {A: 'B', E: 'B', F: 'C', G: 'C', B: 'D', C: 'D'};
assert.ok(e.interact('routing_console'));
assert.ok(e.state.flags.routing_restored);
assert.equal(e.state.xp, 75);
assert.equal(e.state.inventory.length, 1);
assert.equal(observations.length, 4);
e.advanceDialogue();
assert.ok(e.state.flags.routing_understood);
e.interact('routing_console');
assert.equal(observations.length, 4, 'No repeated mastery from solved puzzles');
assert.equal(e.reset('routing'), false, 'Reset must not remove completed progress');
assert.equal(e.state.xp, 75);
e.state.player = {x: 3, y: 9};
e.interact('routing_mentor');
assert.equal(e.state.dialogue.id, 'routing_after', 'NPC remembers the solution');
const store = new Map(), storage = {getItem: k => store.get(k), setItem: (k, v) => store.set(k, v)};
const saves = new SaveSystem(storage, 'course:chunk', 'hash');
assert.ok(saves.save(e));
const restored = new WorldEngine(world);
assert.ok(saves.load(restored));
assert.equal(restored.state.dialogue.id, 'routing_after');
assert.ok(restored.state.flags.routing_restored);
assert.equal(restored.state.xp, 75);
assert.ok(saves.load(restored));
assert.equal(restored.state.xp, 75, 'Loading twice must not duplicate rewards');
assert.equal(restored.state.inventory.length, 1);
assert.equal(new SaveSystem(storage, 'other:chunk', 'hash').load(new WorldEngine(world)), false);
assert.equal(new SaveSystem(storage, 'course:chunk', 'changed').load(new WorldEngine(world)), false);
assert.equal(new SaveSystem({setItem() {throw Error('quota');}}, 'x', 'x').save(e), false);
const forged = e.snapshot();
forged.puzzles.sequence.solved = true;
forged.flags.sequence_restored = true;
forged.player = {x: -100, y: NaN};
const clean = new WorldEngine(world); clean.restore(forged);
assert.equal(clean.state.puzzles.sequence.solved, false);
assert.equal(clean.state.flags.sequence_restored, undefined);
assert.equal(clean.state.player.x, world.player.x);
const stranded = new WorldEngine(world);
stranded.restore({player:{x:30,y:9},puzzles:{}});
assert.equal(stranded.state.player.x, world.player.x, 'Corrupt save cannot strand the player behind a locked gate');
const hardware = clean.puzzles.get('hardware');
clean.state.dialogue = null;
clean.state.quests.hardware_quest = 'active';
// A crate stuck in a corner remains recoverable; completed earlier quests survive reset.
clean.state.puzzles.hardware.blocks[0] = {x: 1, y: 1};
assert.ok(clean.reset('hardware'));
assert.deepEqual(clean.state.puzzles.hardware.blocks, hardware.mechanics.blocks.map(b => ({x:b.x,y:b.y})));
assert.ok(clean.state.flags.routing_restored);
const bus = new EventBus(); let count = 0;
const off = bus.on('sample', () => count++); bus.emit('sample'); off(); bus.emit('sample'); assert.equal(count, 1);
const tracker = BKT.createTracker({scope:'world-test', storage});
const before = tracker.get('network.routing').mastery;
for (const observation of observations) tracker.observe(observation.skill, observation.correct, {label: observation.label, observations: observation.observations});
assert.ok(tracker.get('network.routing').mastery > before);
assert.equal(tracker.get('network.load_balance').lastObservations.hintsUsed, 1);
assert.equal(tracker.get('network.load_balance').lastObservations.solutionSteps, 2);
const guarded = new WorldEngine(world);
guarded.restore({dialogue:{id:'routing_after',line:0},puzzles:{}});
assert.equal(guarded.state.dialogue, null, 'A corrupt save cannot trigger a success dialogue before solving');
console.log('OK: errors, physical consequences, reset, dialogue, save isolation and skill telemetry.');
